### ISSUE TITLE
Logo wanted

### ISSUE THREAD

**Issue by artalar** [artalar/stylerun#1]
I think it may be something like "`<style>`_`run`_".

Place it [here](https://github.com/artalar/stylerun/blame/main/README.md#L7) or in the comments.

Also we need an open graph image (paste it in the comments) ![repository-open-graph-template](https://user-images.githubusercontent.com/27290320/106711093-0a174200-6608-11eb-8c00-35d5c0cbf5c7.png)

You may add your authorship, but later it will be replaced by a standard card of https://allcontributors.org.

A few contextual pictures for inspiration:

![image](https://user-images.githubusercontent.com/27290320/106698775-8acb4380-65f2-11eb-9aa7-fc1bf71eb01d.png)

![image](https://user-images.githubusercontent.com/27290320/106698857-bcdca580-65f2-11eb-80ea-b7f2e6b6017e.png)

![image](https://user-images.githubusercontent.com/27290320/106698929-e39adc00-65f2-11eb-8fab-364ba8879de7.png)

![image](https://user-images.githubusercontent.com/27290320/106699013-0e853000-65f3-11eb-854d-675385541a11.png)

![image](https://user-images.githubusercontent.com/27290320/106699071-2957a480-65f3-11eb-9d5d-424c52ba0170.png)

**Comment by kancurochat** [comment]
This is the design I came up with. Hope you like it! I don't know how to make an open graph image yet, but if you like the design I could learn in a moment. 
![Stylerun](https://user-images.githubusercontent.com/54439779/106740131-ea851700-6611-11eb-92d6-8ec776f075e1.png)

**Comment by artalar** [comment]
Hi @kancurochat, it looks interesting! Purple one I like the most, could u please play a little bit with `RUN` (make it italic maybe).

**Comment by kancurochat** [comment]
Do you like it more this way?
![Stylerun_italics](https://user-images.githubusercontent.com/54439779/106742136-86b01d80-6614-11eb-8a66-3ce53c0a3835.png)

**Comment by artalar** [comment]
Yeah! `RUN` a little higher than `style`. Maybe make it centered by horizontal or is this intentional?

**Comment by kancurochat** [comment]
It was intentional, but I could align the `RUN` with `style`. I'll do it as soon as I get home!

**Comment by kancurochat** [comment]
Here it is!
![Stylerun_aligned](https://user-images.githubusercontent.com/54439779/106879842-904c8a80-66d3-11eb-9998-4fb232263510.png)

**Comment by artalar** [comment]
🤔🤔🤔  not easy to choose. The first one is looking good now =D
I like the concept, so choose your favorite one, and let's publish it.

**Comment by kancurochat** [comment]
My favourite is the yellow one so, if you like it too, I guess that we found your first logo x)

**Comment by artalar** [comment]
@kancurochat ok, take it!

**Comment by kancurochat** [comment]
I'll make a pull request this night. Just one more thing, how do I make an open graph image?

**Comment by artalar** [comment]
[Here](https://user-images.githubusercontent.com/27290320/106711093-0a174200-6608-11eb-8c00-35d5c0cbf5c7.png) an example of OG image. The rules are simple: try to use the same aspect ratio and zoom out the picture to leave 40pt border.

**Comment by kancurochat** [comment]
Hey @artalar! I'm having some kind of trouble to use the image in the README.md. Maybe I'm missing some information, it's my first time contributing in this way.

**Comment by artalar** [comment]
@kancurochat how can I help? I [just fix and uncomment logo in the readme](https://github.com/artalar/stylerun/blame/main/README.md#L6), so all you need is make PR with `logo.svg` in the root of the repo. Don't worry about OG image, start with a logo and see will below.

**Comment by kancurochat** [comment]
I'm trying to make it work in a fork of your repository but it does not use the image. I don't know what's wrong.

**Comment by artalar** [comment]
If u mean `readme.md`, it not work becouse the logo url is linked to my `main` branch and it will not work untill we merge PR.

**Comment by artalar** [comment]
#8
